### ISSUE TITLE
You scooped me!!!! (not really)

### ISSUE THREAD

**Issue by Hellisotherpeople** [koaning/human-learn#29]
The interactive "build your own model" is such a fking good idea I've been talking about trying to build this forever in my own circles! I'm glad to see someone finally do it!! 

Things you need to do: 

1. Make a cool VR demo with 3D projection of datapoints and using controls to build decision boundries and to visualize stuff 
2. Add lots of different dimensionality reduction algorithms
3. Add some VAEs or other generative models to let people hallucinate hypothetical points to get an idea of what each part of the decision boundry is doing. Anything which supports inverse transformations is applicable here. 
4. Add visualization of the exact function that the user creates. Are you building it with piece-wise rules? I want the model to be exportable and directly interpretable mathematically. 
5. Add in local explanation models like LIME and visualize the LIME process as embeddings tons of points really close to your own for feature attribution.

I may do some work on this if you are interested but this is F*ING AWESOME!

**Comment by koaning** [comment]
I'm happy to read the enthousiasm but these suggestions feel outside of the scope of this project. We want to make it easier to add simple domain rules to existing scikit-learn compatible machine learning models. Simplicity is a goal here so this project will only focus on tabular data.

1. VR with 3D projections is a nifty idea, but well outside of scope.
2. Dimension Reduction algorithms are already available, no need to have them here. 
3. VAEs are too complex to consider "domain rule". 
4. We offer tools to draw the exact function that the user creates, therefore the visualisation is already there? 
5. I don't expect LIME won't work well in situations that are drawn or where a custom function is used. Locally, the terrain isn't smooth. Also here, there's less of a need for LIME because the user directly tells the model what to do.
